apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: gitlab-merger-bot
version: 1.2.1
home: https://github.com/pepakriz/gitlab-merger-bot
maintainers:
  - name: pepakriz
    email: pepakriz@gmail.com
